-- KPI - Total Revenue
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM GOLD_BOOKING_CLEAN;

-- KPI - Total Bookings
SELECT COUNT(*) AS TOTAL_BOOKING
FROM GOLD_BOOKING_CLEAN;

-- KPI - Avg Booking Value
SELECT AVG(TOTAL_AMOUNT) AS AVG_BOOKING_VALUE
FROM GOLD_BOOKING_CLEAN;

-- KPI - Total Guests
SELECT SUM(NUM_GUEST) AS TOTAL_GUESTS
FROM GOLD_BOOKING_CLEAN;

-- Line Chart - Monthly Revenue
SELECT DATE, TOTAL_REVENUE
FROM GOLD_AGG_DAILY_BOOKING
ORDER BY DATE;

-- Line Chart - Monthly Bookings
SELECT DATE, TOTAL_BOOKING
FROM GOLD_AGG_DAILY_BOOKING
ORDER BY DATE;

-- Bar Chart - Top Cities By Revenue
SELECT HOTEL_CITY, TOTAL_REVENUE
FROM GOLD_AGG_HOTEL_CITY_SALES
WHERE TOTAL_REVENUE IS NOT NULL
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- Bar Chart - Bookings By Status
SELECT BOOKING_STATUS, COUNT(*) AS TOTAL
FROM GOLD_BOOKING_CLEAN
GROUP BY BOOKING_STATUS;

-- Bar Chart - Bookings By Room Type
SELECT ROOM_TYPE, COUNT(*) AS TOTAL_BOOKING
FROM GOLD_BOOKING_CLEAN
GROUP BY ROOM_TYPE
ORDER BY TOTAL_BOOKING DESC;