-- Create Database
CREATE DATABASE HOTEL_DB;

-- Create File Format
CREATE OR REPLACE FILE FORMAT FF_CSV
 TYPE = 'CSV'
 FIELD_OPTIONALLY_ENCLOSED_BY = '"'
 SKIP_HEADER = 1
 NULL_IF = ('NULL', 'null', '')

-- Create Stage
CREATE OR REPLACE STAGE STG_HOTEL_BOOKINGS
 FILE_FORMAT = FF_CSV;

-- Create Table Bronze_Hotel_Booking
CREATE TABLE BRONZE_HOTEL_BOOKING (
 BOOKING_ID STRING,
 HOTEL_ID STRING,
 HOTEL_CITY STRING,
 CUSTOMER_ID STRING,
 CUSTOMER_NAME STRING,
 CUSTOMER_EMAIL STRING,
 CHECK_IN_DATE STRING,
 CHECK_OUT_DATE STRING,
 ROOM_TYPE STRING,
 NUM_GUEST STRING,
 TOTAL_AMOUNT STRING,
 CURRENCY  STRING,
 BOOKING_STATUS STRING
);

-- Loading Data from Stage to Bronze table
COPY INTO BRONZE_HOTEL_BOOKING
FROM @STG_HOTEL_BOOKINGS
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV')
ON_ERROR = 'CONTINUE';

SELECT * FROM BRONZE_HOTEL_BOOKING LIMIT 50;

-- Create Table Silver_Hotel_Booking
CREATE TABLE SILVER_HOTEL_BOOKING (
 BOOKING_ID VARCHAR,
 HOTEL_ID VARCHAR,
 HOTEL_CITY VARCHAR,
 CUSTOMER_ID VARCHAR,
 CUSTOMER_NAME VARCHAR,
 CUSTOMER_EMAIL VARCHAR,
 CHECK_IN_DATE DATE,
 CHECK_OUT_DATE DATE,
 ROOM_TYPE VARCHAR,
 NUM_GUEST INTEGER,
 TOTAL_AMOUNT FLOAT,
 CURRENCY  VARCHAR,
 BOOKING_STATUS VARCHAR
);

--Checking for errors
SELECT CUSTOMER_EMAIL
FROM BRONZE_HOTEL_BOOKING
WHERE NOT (CUSTOMER_EMAIL LIKE '%@%.%')
OR CUSTOMER_EMAIL IS NULL;

SELECT TOTAL_AMOUNT
FROM BRONZE_HOTEL_BOOKING
WHERE TRY_TO_NUMBER(TOTAL_AMOUNT) < 0;

SELECT CHECK_IN_DATE, CHECK_OUT_DATE
FROM BRONZE_HOTEL_BOOKING
WHERE TRY_TO_DATE(CHECK_OUT_DATE) < TRY_TO_DATE(CHECK_IN_DATE);

SELECT DISTINCT BOOKING_STATUS
FROM BRONZE_HOTEL_BOOKING;

-- Inserting Cleaned data to Silver Layer
INSERT INTO SILVER_HOTEL_BOOKING
SELECT 
BOOKING_ID,
HOTEL_ID,
INITCAP(TRIM(HOTEL_CITY)) AS HOTEL_CITY,
CUSTOMER_ID,
INITCAP(TRIM(CUSTOMER_NAME)) AS CUSTOMER_NAME,
CASE
  WHEN CUSTOMER_EMAIL LIKE '%@%.%' THEN LOWER(TRIM(CUSTOMER_EMAIL))
  ELSE NULL
END AS CUSTOMER_EMAIL,
TRY_TO_DATE(NULLIF(CHECK_IN_DATE, '')) AS CHECK_IN_DATE,
TRY_TO_DATE(NULLIF(CHECK_OUT_DATE, '')) AS CHECK_OUT_DATE,
ROOM_TYPE,
NUM_GUEST,
ABS(TRY_TO_NUMBER(TOTAL_AMOUNT)) AS TOTAL_AMOUNT,
CURRENCY, 
CASE 
 WHEN LOWER(BOOKING_STATUS) IN ('confirmeeed', 'confirmd') THEN 'Confirmed'
 ELSE BOOKING_STATUS
END AS BOOKING_STATUS
FROM BRONZE_HOTEL_BOOKING
WHERE 
 TRY_TO_DATE(CHECK_IN_DATE) IS NOT NULL
 AND TRY_TO_DATE(CHECK_OUT_DATE) IS NOT NULL
 AND TRY_TO_DATE(CHECK_OUT_DATE) >= TRY_TO_DATE(CHECK_IN_DATE);

SELECT * FROM SILVER_HOTEL_BOOKING LIMIT 30;

-- Create Gold Tables
CREATE TABLE GOLD_AGG_DAILY_BOOKING AS
SELECT
 CHECK_IN_DATE AS DATE,
 COUNT(*) AS TOTAL_BOOKING,
 SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SILVER_HOTEL_BOOKING
GROUP BY CHECK_IN_DATE
ORDER BY DATE;

CREATE TABLE GOLD_AGG_HOTEL_CITY_SALES AS
SELECT 
 HOTEL_CITY,
 SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SILVER_HOTEL_BOOKING
GROUP BY HOTEL_CITY
ORDER BY TOTAL_REVENUE DESC;

CREATE TABLE GOLD_BOOKING_CLEAN AS
SELECT BOOKING_ID, 
 HOTEL_ID, 
 HOTEL_CITY ,
 CUSTOMER_ID ,
 CUSTOMER_NAME ,
 CUSTOMER_EMAIL ,
 CHECK_IN_DATE ,
 CHECK_OUT_DATE ,
 ROOM_TYPE ,
 NUM_GUEST ,
 TOTAL_AMOUNT ,
 CURRENCY  ,
 BOOKING_STATUS 
FROM SILVER_HOTEL_BOOKING;

SELECT * FROM GOLD_AGG_DAILY_BOOKING LIMIT 30;
SELECT * FROM GOLD_AGG_HOTEL_CITY_SALES LIMIT 30;